chore: Updated CI process to correctly build vf packages and copy in dockerfile

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,7 +6,6 @@
 # https://dev.assets.emblstatic.net/vf/{tag}/ (eg v2.1.2 / v2.1.3-alpha.3)
 # https://dev.assets.emblstatic.net/vf/{minor}/ (eg v2.1)
 # https://dev.assets.emblstatic.net/vf/{major}/ (eg v2)
-image: node:18.20.4
 
 variables:
   # project specific variables can be defined here
@@ -21,10 +20,6 @@ variables:
   # Clean up naming constraints by using native GitLab CI predefined variables where possible
   DOCKER_PROJECT_NAME: "${CI_PROJECT_NAME}"
   IMAGE_NAME: "$CI_REGISTRY/$CI_PROJECT_PATH:$DOCKER_PROJECT_NAME-nginx-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID"
-  VM_DEV: "$EXTCORE_DEV_VMS"
-  VM_PROD: "$EXTCORE_PROD_VMS"
-  VM_PATH_STABLE: /var/www/drupal/stable.visual-framework.dev # tags
-  VM_PATH_LATEST: /var/www/drupal/latest.visual-framework.dev # develop
   SSH_OWNER_ID: wd_drupl
   SSH_APACHE_ID: w3_wd01
   S3_BUCKET_DEV: origin.dev.vf.assets.emblstatic.net
@@ -43,6 +38,7 @@ include:
   - template: Jobs/SAST-IaC.gitlab-ci.yml
 
 stages:
+  - package
   - build
   - test
   - security-scan        # ← new: all security scanning runs here, after build
@@ -109,6 +105,52 @@ nginx_container_scanning:
     CS_REGISTRY_USER: "gitlab-ci-token"
     CS_REGISTRY_PASSWORD: "$CI_JOB_TOKEN"
 
+####################################
+# Package code
+####################################
+.template_package: &package_template
+  stage: package
+  image: node:18.20.4
+  script:
+    - echo "Packaging code..."
+    - yarn global add gulp-cli # ensure gulp CLI available for gulp tasks
+    - yarn --cwd tools/vf-core install
+    - |
+      # Run vf-core prepare step if a gulpfile exists. Continue on failure
+      if [ -f tools/vf-core/gulpfile.js ] || [ -f tools/vf-core/gulpfile.mjs ] || [ -d tools/vf-core/tasks ]; then
+        (cd tools/vf-core && gulp vf-core:prepare-deploy) || true
+      fi
+    - yarn --cwd tools/vf-component-library install
+    - cd tools/vf-component-library && gulp $PACKAGE_BUILD_COMMAND
+  artifacts:
+    paths:
+      - tools/vf-core/build
+      - tools/vf-component-library/build
+  cache:
+    paths:
+      - node_modules
+      - tools/vf-component-library/node_modules
+  except:
+    - /^.visual-framework\/.*$/
+
+package_dev:
+  <<: *package_template
+  variables:
+    PACKAGE_BUILD_COMMAND: build:dev
+  only:
+    # only match on develop branch, or specific tag patterns
+    - develop
+    - /^v\d+\.\d+\.\d+$/
+    - /^v\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/
+
+package_prod:
+  <<: *package_template
+  variables:
+    PACKAGE_BUILD_COMMAND: build
+  only:
+    # only match on specific tag patterns
+    - /^v\d+\.\d+\.\d+$/
+    - /^v\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/
 
 ####################################
 # BUILD
@@ -121,48 +163,30 @@ nginx_container_scanning:
     - echo "Building images with the following variables:"
     - echo "IMAGE_NGINX - $IMAGE_NGINX"
     - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY # Authenticate to Docker registry using token
-    - docker build -t $IMAGE_NGINX --build-arg ENV=$ENVIRONMENT -f Dockerfile_nginx . # Build NGINX image
+    - docker build -t $IMAGE_NGINX --build-arg ENV=$ENVIRONMENT -f Dockerfile . # Build NGINX image
     - docker push $IMAGE_NGINX   # Push NGINX image
 
 build_dev:
   stage: build
   variables:
     ENVIRONMENT: dev
-  artifacts:
-    paths:
-      - tools/vf-core/build
-      - tools/vf-component-library/build
-  cache:
-    paths:
-      - node_modules
-      - tools/vf-component-library/node_modules
-  except:
-    - /^.visual-framework\/.*$/
   only:
     # only match on develop branch, or specific tag patterns
     - develop
     - /^v\d+\.\d+\.\d+$/
     - /^v\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/
+  needs: [package_dev]
   <<: *build
 
 build_prod:
   stage: build
   variables:
     ENVIRONMENT: prod
-  artifacts:
-    paths:
-      - tools/vf-core/build
-      - tools/vf-component-library/build
-  cache:
-    paths:
-      - node_modules
-      - tools/vf-component-library/node_modules
-  except:
-    - /^.visual-framework\/.*$/
   only:
     # only match on specific tag patterns
     - /^v\d+\.\d+\.\d+$/
     - /^v\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/
+  needs: [package_prod]
   <<: *build
 
 ####################################
@@ -221,18 +245,12 @@ build_prod:
       done
     - echo "🚀 Deploying application"
     - kubectl kustomize k8s/overlays/$OVERLAY_DIR | envsubst | kubectl --namespace=$NAMESPACE apply -f - # Deploy application
-    - sleep 30 # Initial wait for 30 seconds before checking rollout status
 
 deploy_dev:
   stage: deploy
   image: ebiwd/alpine-ssh
   tags:
     - docker
-  before_script:
-    - add-ssh-key ${SSH_OWNER_ID} "${SSH_OWNER_KEY}" ${SSH_APACHE_ID} "${SSH_APACHE_KEY}"
-    - add-search-domain ebi.ac.uk
-  script:
-    - for VM in ${VM_PROD}; do rsync -acv --delete-after tools/vf-component-library/build/. ${SSH_OWNER_ID}@${VM}:${VM_PATH_LATEST}/; done;
   only:
     # only match on develop branch, or specific tag patterns
     - develop
@@ -251,11 +269,6 @@ deploy_prod_hh:
   image: ebiwd/alpine-ssh
   tags:
     - docker
-  before_script:
-    - add-ssh-key ${SSH_OWNER_ID} "${SSH_OWNER_KEY}" ${SSH_APACHE_ID} "${SSH_APACHE_KEY}"
-    - add-search-domain ebi.ac.uk
-  script:
-    - for VM in ${VM_PROD}; do rsync -acv --delete-after tools/vf-component-library/build/. ${SSH_OWNER_ID}@${VM}:${VM_PATH_STABLE}/; done;
   only:
     # only match on specific tag patterns
     - /^v\d+\.\d+\.\d+$/
@@ -273,11 +286,6 @@ deploy_prod_hx:
   image: ebiwd/alpine-ssh
   tags:
     - docker
-  before_script:
-    - add-ssh-key ${SSH_OWNER_ID} "${SSH_OWNER_KEY}" ${SSH_APACHE_ID} "${SSH_APACHE_KEY}"
-    - add-search-domain ebi.ac.uk
-  script:
-    - for VM in ${VM_PROD}; do rsync -acv --delete-after tools/vf-component-library/build/. ${SSH_OWNER_ID}@${VM}:${VM_PATH_STABLE}/; done;
   only:
     # only match on specific tag patterns
     - /^v\d+\.\d+\.\d+$/
